[package]
name = "datamanager"
version = "0.1.0"
edition = "2024"

[dependencies]
mockall = "0.13.1"
once_cell = "1.21.1"
regex = "1.11.1"
tempfile = "3.19.1"

[lib]
name = "datamanager"
path = "src/lib.rs"
